# Generated by Django 5.1.15 on 2026-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('sujet', models.CharField(choices=[('commande', 'Commande dédicacée'), ('question', 'Question'), ('presse', 'Demande presse'), ('autre', 'Autre')], default='question', max_length=20, verbose_name='Sujet')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivé')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
