# Generated by Django 5.1.15 on 2026-05-24 15:50

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='Surtitre')),
                ('titre', models.CharField(blank=True, max_length=120, verbose_name='Titre')),
                ('intro', apps.core.fields.RichTextField(blank=True, verbose_name="Texte d'introduction")),
            ],
            options={
                'verbose_name': 'En-tête /contact/',
                'verbose_name_plural': 'En-tête /contact/',
            },
        ),
    ]
