# Generated by Django 5.1.15 on 2026-05-24 16:30

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Page /contact/', 'verbose_name_plural': 'Page /contact/'},
        ),
        migrations.AddField(
            model_name='contactpage',
            name='merci_eyebrow',
            field=models.CharField(blank=True, max_length=80, verbose_name='Surtitre (page Merci)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='merci_titre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Titre (page Merci)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='merci_message',
            field=apps.core.fields.RichTextField(blank=True, mode='inline', verbose_name='Message de remerciement'),
        ),
    ]
