# Generated by Django 5.1.15 on 2026-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactpage_merci_eyebrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='adresse_postale',
            field=models.TextField(blank=True, verbose_name='Adresse de destination'),
        ),
    ]
