# Generated by Django 5.1.15 on 2026-05-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_message_adresse_postale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(choices=[('commande', 'Commande dédicacée'), ('question', 'Question'), ('presse', 'Demande presse'), ('autre', 'Autre')], default='commande', max_length=20, verbose_name='Sujet'),
        ),
    ]
