# Generated by Django 5.1.15 on 2026-05-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_message_sujet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='adresse_postale',
            field=models.TextField(blank=True, verbose_name='Adresse postale de destination'),
        ),
    ]
