# Generated by Django 5.1.15 on 2026-06-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_message_adresse_postale'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('cb', 'Carte bancaire'), ('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
