# Generated by Django 5.1.15 on 2026-06-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_message_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notified',
            field=models.BooleanField(default=True, verbose_name='Notifié'),
        ),
    ]
