# Generated by Django 5.1.15 on 2026-06-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_message_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='nb_exemplaires',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '24,10 €'), (2, '45,99 €')], null=True, verbose_name="Nombre d'exemplaires"),
        ),
        migrations.AddField(
            model_name='message',
            name='paye',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AddField(
            model_name='message',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Session Stripe'),
        ),
    ]
