# Generated by Django 5.1.15 on 2026-06-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_message_nb_exemplaires_message_paye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='nb_exemplaires',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 exemplaire — 24,10 €'), (2, '2 exemplaires — 45,99 €')], null=True, verbose_name="Nombre d'exemplaires"),
        ),
    ]
