# Generated by Django 5.1.15 on 2026-06-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_message_nb_exemplaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dedicace',
            field=models.BooleanField(default=True, verbose_name='Dédicace souhaitée'),
        ),
        migrations.AddField(
            model_name='message',
            name='mode_livraison',
            field=models.CharField(blank=True, choices=[('point_relais', 'Point Relais'), ('locker', 'Locker (casier)'), ('domicile', 'Domicile')], max_length=20, verbose_name='Mode de livraison'),
        ),
        migrations.AddField(
            model_name='message',
            name='prenom_dedicace',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom pour la dédicace'),
        ),
        migrations.AlterField(
            model_name='message',
            name='adresse_postale',
            field=models.TextField(blank=True, verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(choices=[('commande', 'Commande'), ('question', 'Question'), ('presse', 'Demande presse'), ('autre', 'Autre')], default='commande', max_length=20, verbose_name='Sujet'),
        ),
    ]
