# Generated by Django 5.1.15 on 2026-06-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_message_dedicace_message_mode_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='point_relais_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID point relais'),
        ),
        migrations.AddField(
            model_name='message',
            name='point_relais_libelle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Point relais choisi'),
        ),
    ]
