# Generated by Django 5.1.15 on 2026-06-21 05:51

from django.db import migrations, models


def merge_locker_into_point_relais(apps, schema_editor):
    # L'ancien choix « locker » disparaît : on bascule les commandes existantes
    # sur « point_relais » (relais et lockers sont désormais regroupés).
    Message = apps.get_model('contact', 'Message')
    Message.objects.filter(mode_livraison='locker').update(mode_livraison='point_relais')


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_message_point_relais_id_message_point_relais_libelle'),
    ]

    operations = [
        migrations.RunPython(merge_locker_into_point_relais, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='message',
            name='mode_livraison',
            field=models.CharField(blank=True, choices=[('point_relais', 'Point Relais ou Locker'), ('domicile', 'Domicile')], max_length=20, verbose_name='Mode de livraison'),
        ),
    ]
