# Generated by Django 5.1.15 on 2026-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_alter_message_mode_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='nb_exemplaires',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 exemplaire'), (2, '2 exemplaires')], null=True, verbose_name="Nombre d'exemplaires"),
        ),
    ]
