# Generated by Django 5.1.15 on 2026-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_alter_message_nb_exemplaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='stripe_session_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
