# Generated by Django 5.1.15 on 2026-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_remove_message_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(choices=[('commande', 'Commande'), ('question', 'Question'), ('presse', 'Demande presse'), ('autre', 'Autre')], max_length=20, verbose_name='Sujet'),
        ),
    ]
