# Generated by Django 5.1.15 on 2026-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_alter_message_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='produit',
            field=models.CharField(blank=True, choices=[('livre', 'Le livre'), ('volumes', "Volume(s) à l'unité"), ('integrale', 'Intégrale (3 volumes — 15 CD)'), ('pack', 'Pack Intégrale + Livre')], max_length=20, verbose_name='Offre'),
        ),
        migrations.AddField(
            model_name='message',
            name='volumes',
            field=models.CharField(blank=True, max_length=20, verbose_name='Volumes choisis'),
        ),
    ]
