# Generated by Django 5.1.15 on 2026-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_set_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ip_hash', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='core_visite_date_e92601_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'ip_hash'), name='visite_unique_par_jour')],
            },
        ),
    ]
