# Generated by Django 5.1.15 on 2026-05-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitejournaliere'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitejournaliere',
            name='core_visite_date_e92601_idx',
        ),
    ]
