# Generated by Django 5.1.15 on 2026-05-23 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('seo_title', models.CharField(blank=True, help_text='Titre affiché par Google (~60 caractères). Laisser vide pour titre auto.', max_length=70, verbose_name='Titre SEO')),
                ('seo_description', models.CharField(blank=True, help_text='Description affichée par Google (~150 caractères).', max_length=160, verbose_name='Description SEO')),
                ('og_image', models.ImageField(blank=True, help_text="Image affichée lors d'un partage sur les réseaux sociaux.", null=True, upload_to='og/', verbose_name='Image de partage')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Identifiant URL')),
                ('type', models.CharField(choices=[('dedicace', 'Dédicace / rencontre'), ('news', 'Actualité'), ('presse', 'Presse')], default='news', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publiée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_evenement', models.DateField(blank=True, help_text='Pour les dédicaces et événements.', null=True, verbose_name="Date de l'événement")),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure fin')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('chapo', models.CharField(blank=True, help_text="Phrase d'accroche affichée dans les listes.", max_length=300, verbose_name='Chapeau')),
                ('contenu', models.TextField(blank=True, help_text='HTML autorisé.', verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_evenement', '-date_publication'],
            },
        ),
    ]
