# Generated by Django 5.1.15 on 2026-05-23 15:10

import apps.core.uploads
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.uploads.actualites_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Image affichée lors d'un partage sur les réseaux sociaux.", null=True, upload_to=apps.core.uploads.og_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Image de partage'),
        ),
    ]
