# Generated by Django 5.1.15 on 2026-05-23 15:50

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_alter_actualite_image_alter_actualite_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='contenu',
            field=apps.core.fields.RichTextField(blank=True, verbose_name='Contenu'),
        ),
    ]
