# Generated by Django 5.1.15 on 2026-05-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0005_actualiteimage_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualite',
            name='image',
        ),
    ]
