# Generated by Django 5.1.15 on 2026-05-29 15:39

import apps.core.fields
import apps.core.uploads
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0009_actualiteimage_legende'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualiteImageContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Plus le nombre est petit, plus l'image apparaît tôt.", verbose_name='Ordre')),
                ('alt', models.CharField(blank=True, help_text="Décrit l'image pour les lecteurs d'écran. Laisser vide reprend le titre du parent.", max_length=180, verbose_name='Texte alternatif')),
                ('legende', apps.core.fields.RichTextField(blank=True, help_text="Texte affiché sous l'image dans le carrousel. Gras / italique autorisés.", mode='inline', verbose_name='Légende')),
                ('image', models.ImageField(upload_to=apps.core.uploads.actualites_contenu_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Image')),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_contenu', to='actualites.actualite', verbose_name='Actualité')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
    ]
