# Generated by Django 5.1.15 on 2026-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('auteur', models.CharField(max_length=120, verbose_name='Auteur')),
                ('source', models.CharField(blank=True, help_text="Optionnel : ville, lien, contexte (ex. 'Mairie de Pouillon, Facebook').", max_length=200, verbose_name='Source')),
                ('texte', models.TextField(verbose_name='Texte')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('mis_en_avant', models.BooleanField(default=False, help_text="Affiché dans le carrousel de la page d'accueil.", verbose_name='Mis en avant')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
