# Generated by Django 5.1.15 on 2026-05-23 15:50

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temoignages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignage',
            name='texte',
            field=apps.core.fields.RichTextField(verbose_name='Texte'),
        ),
    ]
