# Generated by Django 5.1.15 on 2026-05-24 15:46

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temoignages', '0003_temoignagespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignage',
            name='texte',
            field=apps.core.fields.RichTextField(mode='inline', verbose_name='Texte'),
        ),
    ]
