# Contenu des 3 volumes de l'intégrale « Jacques Bertin — Le chant d'un homme ».
# Source : « Titres des chansons de l'intégrale Bertin.pdf ». Données figées
# (pas en base) : affichées dans une modale « voir le contenu » sous chaque
# volume du formulaire de commande. Chaque volume = 5 CD ; les pistes sont
# auto-numérotées à l'affichage, on ne stocke que les titres dans l'ordre.

VOLUMES_CONTENU = {
    1: {
        "sous_titre": "5 CD · 137 chansons · 1967–1988",
        "note": "* Texte lu par Jacques Doyen",
        "cds": [
            ("CD 1", [
                "Corentin",
                "J'ai vu ses yeux",
                "J'aurai une vache nouvelle",
                "Amants",
                "Un grand châle lilas",
                "Les Ponts-de-Cé",
                "On a découvert l'Amérique",
                "Faut-il être fou ?",
                "Les Chansons de temps passé",
                "On se croit un peu poète",
                "File",
                "Compagnons",
                "Revoilà le soleil",
                "Les Mots et les couleurs",
                "Un jour on meurt",
                "Chanter",
                "Hélène",
                "L'Amour",
                "La Non-supplique",
                "Le Grenier",
                "Je débarquais",
                "J'avais mon âme",
                "Le Fou de Dieu",
                "La Mort",
                "Hélène (version 45 tours)",
                "La Bretagne",
            ]),
            ("CD 2", [
                "Je voudrais une fête étrange et très calme",
                "La Lampe du tableau de bord",
                "A la pointe nue de l'averse",
                "Les Anglais bombardaient les ponts",
                "Si loin offerte parfumée",
                "Je connais des filles superbes",
                "Je suis celui qui court",
                "Partir encore",
                "Je suis ce train de choux-fleurs",
                "Louvigné-du-Désert",
                "A celle que je ne verrai plus",
                "Je parle pour celui qui a manqué le train",
                "Si je savais les mots",
                "Claire",
                "Je signe *",
                "Tu parles de la vie",
                "Amitié, claie ouverte",
                "Je ne donne que l'amitié *",
                "Un instant",
                "Cette fille",
                "Ne parlez pas",
                "Je sonne chez vous",
                "Marche dans la banlieue *",
                "Matin",
                "Ils savaient *",
                "Laissez une fenêtre ouverte",
                "Pour le jour de ma mort *",
                "Roman",
                "Trois bouquets",
                "Les Grands poètes sont comme des fleuves silencieux",
                "Portrait d'Aude",
                "Qu'est-ce qui passe ici si tard",
                "Rappelle-toi le temps qu'il fait (chanson créée pour l'émission télévisée de Georges Ferraro « Le Nouveau printemps de Mémé Jeanne »)",
                "Voilà, c'est cette nuit",
            ]),
            ("CD 3", [
                "En vieillissant",
                "A Besançon",
                "Un soir mon fils",
                "Morte pour des idées (sur des photos de la répression en Turquie)",
                "Mon frère est venu",
                "Le Temps a passé comme un charme",
                "Vous êtes passés dans cette vie",
                "J'ai peu de choses à dire",
                "Ambassade du Chili",
                "Ceux qui sont morts tués par balles",
                "Ce que dit Benoist",
                "Dure à passer",
                "Permanence du fleuve",
                "Paroisse",
                "A Julos",
                "Celle qui avait les cheveux dans les reins",
                "Chanson de la plus grande confiance",
                "L'Enfant toussait de l'autre côté du mur",
                "Pas pareil",
                "Gens de Chalonnes",
                "Menace",
                "Carnet",
                "Génération",
                "Le Vieux bonheur",
                "La nuit on ne peut…",
                "Au docteur L.",
                "Souveraine",
            ]),
            ("CD 4", [
                "Domaine de joie",
                "Colline",
                "Ils s'allongent côte à côte",
                "Petit coucher",
                "Je te rencontrerai dans un rêve inversé",
                "Je vais à l'amitié comme à des auberges",
                "Mère chantez-moi la chanson",
                "L'Annuaire du téléphone (du Gers)",
                "Où tu t'en vas ?",
                "Le Voyage",
                "Une attente",
                "Ballade de la visite au bout du monde",
                "Goût d'ail",
                "Ta prison",
                "Brise marine",
                "Petit homme, c'est l'heure de faire dodo",
                "Un soir, mon fils",
                "Maintenant que la jeunesse (Louis Aragon – Lino Leonardi)",
                "Le Temps de vivre (Henri Gougaud – Jean Bertola)",
                "La Chanson de Tessa (Jean Giraudoux – Maurice Jaubert)",
                "L'Aube sur le Jardin des Plantes (Jean-Max Brua)",
                "Noël (Madame à minuit) (Luc Bérimont – Léo Ferré)",
                "Amis soyez toujours (Jean Vasca)",
                "Stanislas (Rendez-vous) (Ricet-Barrier & Bernard Lelou)",
                "Les Voiles du bateau (Bernard Dimey – Henri Salvador)",
                "Gennevilliers au bout du monde (Jean Sommer)",
                "Les Chants des hommes (Nazim Hikmet – André Grassi)",
            ]),
            ("CD 5", [
                "Syracuse (Bernard Dimey – Henri Salvador)",
                "A Paris dans chaque faubourg (Complainte du film « 14 Juillet »)",
                "Des mains",
                "Quai des Chartrons",
                "Les Grands départs",
                "La Maison au bord de la route",
                "Les Biefs",
                "Les Noyés",
                "Où tu es, tu es bien",
                "Redon",
                "La Draguée haute",
                "Ma vie, mon œuvre",
                "Nous reconnaître",
                "La Nuit et le visage",
                "Et je crois à la loi",
                "Buffet de gare",
                "La Longue larme",
                "Bérimont-Cadou-Meaulnes",
                "Le Voyageur",
                "Je t'attends aux grilles des routes",
                "Retour à Poigny",
                "Vie, ma vie",
                "Le Cheval",
            ]),
        ],
    },
    2: {
        "sous_titre": "5 CD · 122 chansons · 1988–2013",
        "note": "",
        "cds": [
            ("CD 1", [
                "Passer l'hiver",
                "L'Etoile du matin",
                "Mario",
                "Cette année s'envole ma jeunesse",
                "La Leçon de piano",
                "Berceuse",
                "Nuit d'été",
                "Cheval perdu",
                "La Pionne du lycée des filles",
                "Qui tire les ficelles du vent ?",
                "Cimetière des théâtres morts",
                "Trois bouquets",
                "Elise",
                "Décembre",
                "Retour à Chalonnes",
                "Paysage",
                "Merci pour les jours heureux",
                "J'allais vers toi du fond de ma souffrance",
                "J'allais vers toi comme dans l'eau la paille",
                "Parc Borelly, un dimanche",
                "Marseille, quand tu dors",
                "Je veillerai sur toi surtout sans que jamais tu saches",
                "La Tristesse",
                "Une grange",
                "L'Ephémère et la durée",
                "Le Blé, le moût",
                "L'Eternité à Denfer",
                "Je vous écris pour vous dire que si l'on souffre",
            ]),
            ("CD 2", [
                "La Bonté des faibles",
                "Tableau",
                "Hôtel du Grand retour",
                "La Femme triste",
                "L'Or pur",
                "Vieil avare",
                "C'est un amour ancien perdu",
                "L'Espérance",
                "Bar de la Jetée à 20 heures",
                "L'Europe",
                "Chambre 16",
                "Pascaline",
                "Je t'attendais",
                "Tous les amours se ressemblent (Chambre 27)",
                "La Méchanceté (Chambre 402, deux heures du matin)",
                "L'Aube à Cassis",
                "La Foi",
                "Le Soir",
                "Je voudrais être à la fois cet enfant qui passe…",
                "Petite chanson française",
                "Rivière",
                "Les Traces des combats",
                "Lorsque la mère meurt, on va…",
                "Paroisse",
                "A la messe du soir, en 1955",
                "Les Etudiants au Café Rihour, à Lille, en 1967",
                "L'Espérance",
                "Comme il est dur de vieillir",
            ]),
            ("CD 3", [
                "La Paix",
                "Chalonnes",
                "Le Grand bras",
                "Etranges amours fidèles",
                "Le Messager",
                "Petit Anjou",
                "La Douleur",
                "Brassensienne",
                "Le Rêveur",
                "A la merveille",
                "Comme si… comme si…",
                "La Solitude",
                "La Bonté",
                "L'Essentiel",
                "Les Tonnelles",
                "La Grande crue de 2001",
                "Le Bonheur des autres",
                "Chanson du retour",
                "Quand recevrons-nous des renforts, mon âme ?",
                "Prose des jours longs",
                "La Cheminée",
                "J'ai cherché le secret des roses",
                "La Fidélité",
                "La Jeune fille blonde",
                "Dans la mort",
                "La Loire à l'Alleud",
                "Gloire à vous ! (Les Gens de l'ombre)",
            ]),
            ("CD 4", [
                "Forteresse",
                "Miserere",
                "Hommage (6 Juin 1944)",
                "A un fils",
                "Encore vous…",
                "Que le temps s'efface",
                "La Belle fille aux yeux verts (à Québec)",
                "Aux funérailles au funambule",
                "Le Cœur troué",
                "Ce mal",
                "Le Pouvoir du chant",
                "La Loire",
                "Pour la fin des errances",
                "Ah ! vieil ami…",
                "Des chansons d'homme",
                "La Mâle mort",
                "Mes amies",
                "Vision à la guinguette",
                "Le Passé ?",
                "Un homme",
                "Comme un pays",
            ]),
            ("CD 5", [
                "Les Livres",
                "Curés rouges",
                "Gros bourgs français",
                "Deux mots",
                "La Maison basse",
                "Maisons… maisons…",
                "Madame,",
                "Les Grands châteaux abandonnés",
                "L'Hiver en France",
                "l'Hôtel",
                "Paxaafère !",
                "Fais comme si",
                "Donnez des nouvelles",
                "Béatitudes",
                "Un mur",
                "Amis, soyez toujours (UniSon)",
                "Adieu, amis de ma jeunesse (UniSon)",
                "L'Internationale",
            ]),
        ],
    },
    3: {
        "sous_titre": "5 CD · 125 chansons dont 13 inédites, sauvées des eaux · 1977–2022",
        "note": "",
        "cds": [
            ("CD 1", [
                "Hymne",
                "L'Espoir, dédié à Jean-Claude Guillebaud",
                "Les Cris d'écoliers dans les cours (Lucien Massion – Philippe Bizais)",
                "Le Bois amical (Paul Valéry, Album de vers anciens, Gallimard, 1929 – Jacques Bertin)",
                "Hymne des jardins",
                "La Bicyclette d'argent (Luc Bérimont – Jacques Douai)",
                "Aux Amis réunis",
                "Qu'on me rende l'espérance",
                "La Lumière dans la coulisse (Jacques Bertin – Philippe Geoffroy)",
                "Je suis plus près de toi (Luc Bérimont – Lise Médini)",
                "Vœux du poète (Valéry Larbaud, Les Poésies de A.O. Barnabooth, Gallimard, 1923 – Jacques Bertin)",
                "A la claire fontaine (Traditionnel)",
                "Brave marin (Traditionnel)",
                "Mon sombre amour (Louis Aragon – Jacques Douai)",
                # Titre tronqué dans le PDF source (« … 1918 – ») : à compléter par Bruno.
                "If (Rudyard Kipling, adaptation par André Maurois, in Les Silences du colonel Bramble, 1918 – …)",
                "Fini, le bistro à Dédé",
                "Qu'avons-nous fait du paradis ?",
                "A force de solitude, j'ai acquis l'art de la mer",
                "Le Jour baisse ; la pluie, à la clarté des lampes…",
                "J'aime rien – et alors ?",
                "Être vieux ?",
                "Je suis monté là-haut…",
                "Jours en allés (Lucien Massion – Jacques Bertin)",
                "Ami, j'ai bien reçu ta lettre",
                "Notre-Dame de l'amitié (dédié à Michèle Bailet)",
                "C'était bien (Le Petit bal perdu) (Robert Nyel – Gaby Verlor)",
            ]),
            ("CD 2", [
                "Qu'as-tu fait de ta jeunesse ? — J'ai aimé (dédié à Sylvie Fichelson)",
                "Merci pour tout, merci pour l'espérance…",
                "Une attente",
                "Indien (Prologue avec la scène vide et la salle allumée)",
                "Carnet",
                "Sourcier",
                "Les Grands poètes",
                "Paroisse",
                "A Besançon",
                "Ambassade du Chili",
                "Le Temps a passé comme un charme",
                "Dragueur",
                "Dernier avertissement",
                "Domaine de joie",
                "Je voudrais une fête étrange et très calme",
                "Des mains",
                "Les Biefs",
                "Les Tarés",
                "L'Invitation au voyage (Charles Baudelaire – Reinhardt Wagner)",
                "La Fille dont auquel (Jacques Bertin – Michel Roques)",
                "Un voyage",
                "Ballade (Jean Sommer)",
                "Les Chants des hommes (Nazim Hikmet – André Grassi)",
            ]),
            ("CD 3", [
                "Les Noyés",
                "Je voudrais une fête étrange et très calme",
                "Carnet",
                "L'Invitation au voyage (Charles Baudelaire – Reinhardt Wagner)",
                "Les Nouvelles du soir (Philippe Jaccottet – Jacques Bertin)",
                "Carnet",
                "Le Voyageur (Luc Bérimont – Reinhardt Wagner)",
                "Je te rencontrerai dans un rêve inversé",
                "Les Grands départs",
                "Des mains",
                "L'Etang chimérique (Léo Ferré)",
                "Les Lèvres bleues",
                "Le Bateau espagnol (Léo Ferré)",
                "Les Noyés",
                "Un voyage",
                "Noël (Luc Bérimont – Léo Ferré)",
                "Je t'attends aux grilles des routes (Luc Bérimont – Reinhardt Wagner)",
                "La Chanson de Tessa (Jean Giraudoux – Maurice Jaubert)",
                "Les Poètes assassinés (Henri Gougaud)",
                "L'Affiche rouge (Louis Aragon – Léo Ferré)",
                "Le Bonheur",
                "Les Chants des hommes (Nazim Hikmet – André Grassi)",
                "A la place du ciel (René-Guy Cadou – Jacques Douai)",
            ]),
            ("CD 4", [
                "Maintenant que la jeunesse (Louis Aragon – Lino Leonardi)",
                "Je voudrais une fête étrange et très calme",
                "La Lampe du tableau de bord",
                "Mon sombre amour (Louis Aragon – Jacques Douai)",
                "L'Etang chimérique (Léo Ferré)",
                "Démons et merveilles (Jacques Prévert – Marcel Thiriet)",
                "Colchiques dans les prés (Jacqueline Claude – Francine Cockenpot)",
                "Le Testament (François Villon – Félix Leclerc)",
                "Les Loupiots (Aristide Bruant – Lino Leonardi)",
                "La Commune est en lutte (Jean-Roger Caussimon – Philippe Sarde)",
                "Complainte du partisan (Emmanuel D'Astier de la Vigerie – Anna Marly)",
                "Ballade du passant (Claude Semal)",
                "Noël (Luc Bérimont – Léo Ferré)",
                "Le Messager",
                "Les Feuilles mortes (Jacques Prévert – Joseph Kosma)",
                "Chanson vieillotte (Gilles Vigneault – Claude Léveillée)",
                "Le Soir",
                "La Fidélité",
                "Quand tu voudras",
                "Aller vers la paix",
                "Adieu foulards (Traditionnel)",
                "Retour à Chalonnes",
                "Je voudrais une fête étrange et très calme",
                "Les Nouvelles du soir (Philippe Jaccottet – Jacques Bertin)",
                "La Ballade du passant (Claude Semal)",
                "Gloire à vous (Jacques Bertin – Traditionnel)",
            ]),
            ("CD 5", [
                "Trois bouquets",
                "Génération",
                "Quand recevrons-nous des renforts, mon âme ?",
                "Actualités (Stéphane Golmann – Albert Vidalie)",
                "Paroisse",
                "La Fidélité",
                "Donnez-moi une femme triste",
                "Madame…",
                "La Jeune fille blonde",
                "La Beauté du monde – Anne-Marie…",
                "Que faire ?",
                "Les Chants des hommes (Nazim Hikmet – André Grassi)",
                "Les Biefs",
                "Changer la vie (avec le groupe Uni Son)",
                "Autoportrait en bœuf",
                "La Maison de l'institutrice",
                "Petite chanson",
                "Beaux trains",
                "La Gloire",
                "L'Auberge des Quatre Routes",
                "Comptine",
                "Changer de nom",
                "Con comme un homme",
                "La Scoutériste",
                "Le Pêcheur",
                "Y'a que les vieux amis",
                # Titre tronqué dans le PDF source (« 27. J'ai ») : à compléter par Bruno.
                "J'ai…",
            ]),
        ],
    },
}
