# Generated by Django 5.1.15 on 2026-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('email_contact', models.EmailField(default='boulaisbruno@free.fr', max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('ville', models.CharField(blank=True, default='Misson (40)', max_length=100, verbose_name='Ville')),
                ('texte_pied_de_page', models.TextField(blank=True, help_text='Quelques mots affichés dans le footer (HTML autorisé).', verbose_name='Texte du pied de page')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL Instagram')),
                ('bandeau_actif', models.BooleanField(default=False, help_text='Affiche un bandeau en haut du site annonçant la prochaine dédicace.', verbose_name='Afficher le bandeau dédicace')),
                ('bandeau_texte', models.CharField(blank=True, max_length=200, verbose_name='Texte du bandeau')),
                ('bandeau_url', models.URLField(blank=True, verbose_name='Lien du bandeau')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
