# Generated by Django 5.1.15 on 2026-05-23 15:50

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='texte_pied_de_page',
            field=apps.core.fields.RichTextField(blank=True, help_text='Quelques mots affichés dans le footer.', verbose_name='Texte du pied de page'),
        ),
    ]
