# Generated by Django 5.2.15 on 2026-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_alter_parametres_texte_pied_de_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='poids_emballage_g',
            field=models.PositiveIntegerField(default=50, help_text='Ajouté une fois au poids total de la commande pour le calcul des frais de port.', verbose_name="Poids d'emballage (grammes)"),
        ),
    ]
