# Generated by Django 5.2.15 on 2026-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_parametres_poids_emballage_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='bandeau_actif',
            field=models.BooleanField(default=False, help_text='Affiche un bandeau en haut du site (dédicace, boutique, actualité…).', verbose_name="Afficher le bandeau d'annonce"),
        ),
    ]
