# Generated by Django 5.2.15 on 2026-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_alter_parametres_bandeau_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='bandeau_chapeau_texte',
            field=models.CharField(blank=True, default='Vous avez des articles en attente de commande — cliquez ici pour finaliser.', help_text="Affiché à la place de l'annonce quand le visiteur a des articles dans son chapeau.", max_length=200, verbose_name='Texte du bandeau « chapeau »'),
        ),
    ]
