# Generated by Django 5.1.15 on 2026-05-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('titre', models.CharField(default='Jacques Bertin, le géant discret de la chanson', max_length=200, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre')),
                ('pitch_court', models.CharField(blank=True, help_text="Une ou deux phrases d'accroche, visible sur la page d'accueil.", max_length=300, verbose_name='Pitch court')),
                ('pitch_long', models.TextField(blank=True, help_text='Texte riche présentant le livre sur sa page dédiée (HTML autorisé).', verbose_name='Présentation longue')),
                ('sommaire', models.TextField(blank=True, help_text='Sommaire du livre (HTML autorisé).', verbose_name='Sommaire')),
                ('extrait', models.TextField(blank=True, help_text='Extrait choisi du livre (HTML autorisé).', verbose_name='Extrait')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='livre/', verbose_name='Couverture')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('editeur', models.CharField(default='Éditions du Petit Pavé', max_length=100, verbose_name='Éditeur')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('prix_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Prix (€)')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livre',
            },
        ),
        migrations.CreateModel(
            name='LienAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('url', models.URLField(verbose_name='Lien')),
                ('description', models.CharField(blank=True, help_text="Optionnelle : ex. 'avec dédicace, envoi Mondial Relay'.", max_length=200, verbose_name='Description')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_achat', to='livre.livre', verbose_name='Livre')),
            ],
            options={
                'verbose_name': "Lien d'achat",
                'verbose_name_plural': "Liens d'achat",
                'ordering': ['position', 'id'],
            },
        ),
    ]
