# Generated by Django 5.1.15 on 2026-05-23 15:10

import apps.core.uploads
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.uploads.livre_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Couverture'),
        ),
    ]
