# Generated by Django 5.1.15 on 2026-05-23 15:50

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0002_alter_livre_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='extrait',
            field=apps.core.fields.RichTextField(blank=True, help_text='Extrait choisi du livre.', verbose_name='Extrait'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='pitch_long',
            field=apps.core.fields.RichTextField(blank=True, help_text='Texte riche présentant le livre sur sa page dédiée.', verbose_name='Présentation longue'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='sommaire',
            field=apps.core.fields.RichTextField(blank=True, help_text='Sommaire du livre.', verbose_name='Sommaire'),
        ),
    ]
