# Generated by Django 5.1.15 on 2026-05-23 17:36

import apps.core.uploads
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0003_alter_livre_extrait_alter_livre_pitch_long_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Plus le nombre est petit, plus l'image apparaît tôt.", verbose_name='Ordre')),
                ('alt', models.CharField(blank=True, help_text="Décrit l'image pour les lecteurs d'écran. Laisser vide reprend le titre du parent.", max_length=180, verbose_name='Texte alternatif')),
                ('image', models.ImageField(upload_to=apps.core.uploads.livre_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Image')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='livre.livre', verbose_name='Livre')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
    ]
