# Generated by Django 5.1.15 on 2026-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0008_livreimage_legende'),
    ]

    operations = [
        migrations.AddField(
            model_name='lienachat',
            name='type',
            field=models.CharField(choices=[('dedicace', 'Avec dédicace'), ('externe', 'Lien externe')], default='externe', help_text='Pilote le surtitre affiché sur la carte (« Avec dédicace » ou « Lien externe »).', max_length=20, verbose_name='Type de lien'),
        ),
    ]
