# Generated by Django 5.1.15 on 2026-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('role', models.CharField(choices=[('auteur', 'Auteur du livre'), ('sujet', 'Sujet du livre')], max_length=20, unique=True, verbose_name='Rôle')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('sous_titre', models.CharField(blank=True, help_text="Ex. 'Chanteur, poète, écrivain' ou 'Auteur, près de Dax'.", max_length=200, verbose_name='Sous-titre')),
                ('annee_naissance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de naissance')),
                ('bio_courte', models.CharField(blank=True, help_text='Pour les vignettes et le pied de page.', max_length=300, verbose_name='Bio courte')),
                ('bio_longue', models.TextField(blank=True, help_text='Texte riche (HTML autorisé).', verbose_name='Biographie')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/', verbose_name='Portrait')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
    ]
