# Generated by Django 5.1.15 on 2026-05-23 15:50

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0002_alter_personne_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='bio_longue',
            field=apps.core.fields.RichTextField(blank=True, help_text='Texte riche : gras, italique, sauts de ligne.', verbose_name='Biographie'),
        ),
    ]
