# Generated by Django 5.1.15 on 2026-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0005_personneimage_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='portrait',
        ),
    ]
