# Generated by Django 5.1.15 on 2026-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0006_personne_drop_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='delai_rotation_s',
            field=models.PositiveSmallIntegerField(default=8, help_text="0 = pas de rotation, l'image d'ordre 1 reste affichée. Sinon délai en secondes entre chaque image.", verbose_name='Délai entre images (secondes)'),
        ),
    ]
