# Generated by Django 5.1.15 on 2026-06-03 15:00

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0008_personneimage_legende'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='citation_auteur',
            field=models.CharField(blank=True, max_length=120, verbose_name='Auteur de la citation'),
        ),
        migrations.AddField(
            model_name='personne',
            name='citation_commentaire',
            field=models.CharField(blank=True, help_text="Quelques mots, affichés sous l'auteur, sur la citation ou son auteur (optionnel).", max_length=300, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='personne',
            name='citation_texte',
            field=apps.core.fields.RichTextField(blank=True, help_text='Phrase mise en exergue sur la page dédiée.', mode='inline', verbose_name='Citation'),
        ),
    ]
