# Generated by Django 5.1.15 on 2026-06-30 19:24

import apps.core.fields
import apps.core.uploads
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiquePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='Surtitre')),
                ('titre', models.CharField(blank=True, max_length=120, verbose_name='Titre')),
                ('intro', apps.core.fields.RichTextField(blank=True, verbose_name="Texte d'introduction")),
            ],
            options={
                'verbose_name': 'En-tête /boutique/',
                'verbose_name_plural': 'En-tête /boutique/',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('reference_commande', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Référence')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('adresse_postale', models.TextField(blank=True, verbose_name='Adresse postale')),
                ('mode_livraison', models.CharField(blank=True, choices=[('point_relais', 'Point Relais ou Locker'), ('domicile', 'Domicile')], max_length=20, verbose_name='Mode de livraison')),
                ('point_relais_id', models.CharField(blank=True, max_length=20, verbose_name='ID point relais')),
                ('point_relais_libelle', models.CharField(blank=True, max_length=255, verbose_name='Point relais choisi')),
                ('dedicace', models.BooleanField(default=False, verbose_name='Dédicace souhaitée')),
                ('prenom_dedicace', models.CharField(blank=True, max_length=100, verbose_name='Prénom pour la dédicace')),
                ('mode_paiement', models.CharField(choices=[('cb', 'Carte bancaire'), ('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20, verbose_name='Mode de paiement')),
                ('montant_articles_cents', models.PositiveIntegerField(default=0, verbose_name='Articles (centimes)')),
                ('frais_port_cents', models.PositiveIntegerField(default=0, verbose_name='Frais de port (centimes)')),
                ('montant_total_cents', models.PositiveIntegerField(default=0, verbose_name='Total (centimes)')),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement (CB lancée)'), ('en_attente_reglement', 'En attente de règlement (chèque/virement)'), ('paye', 'Payé'), ('annule', 'Annulé')], max_length=30, verbose_name='Statut')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, verbose_name='Session Stripe')),
                ('notified', models.BooleanField(default=True, verbose_name='Notifié')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivé')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='Slug')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('prix_cents', models.PositiveIntegerField(verbose_name='Prix (centimes)')),
                ('description', apps.core.fields.RichTextField(blank=True, verbose_name='Description')),
                ('illustration', models.ImageField(blank=True, upload_to=apps.core.uploads.boutique_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Illustration')),
                ('volume_integrale', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Volume 1'), (2, 'Volume 2'), (3, 'Volume 3')], help_text='Si renseigné, la fiche affiche le contenu du volume.', null=True, verbose_name="Volume de l'intégrale")),
                ('dedicacable', models.BooleanField(default=False, verbose_name='Dédicaçable')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': [models.Case(models.When(position=0, then=models.Value(1)), default=models.Value(0), output_field=models.IntegerField()), 'position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('prix_unitaire_cents', models.PositiveIntegerField(verbose_name='Prix unitaire (centimes)')),
                ('quantite', models.PositiveSmallIntegerField(verbose_name='Quantité')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='boutique.commande')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
