# Generated by Django 5.1.15 on 2026-07-06 18:44

from django.db import migrations, models

# Grille de départ (paliers déduits des données de Bruno, livre = intégrale ≈ 500 g).
# Bruno ajuste ensuite en gestion. (poids_max_g, prix_relais_cents, prix_domicile_cents)
TRANCHES_INITIALES = [
    (500, 415, 749),
    (1000, 599, 949),
    (30000, 799, 1099),
]


def seed_tranches(apps, schema_editor):
    TranchePort = apps.get_model("boutique", "TranchePort")
    TranchePort.objects.bulk_create(
        TranchePort(poids_max_g=p, prix_relais_cents=r, prix_domicile_cents=d)
        for p, r, d in TRANCHES_INITIALES
    )


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_produit_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranchePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('poids_max_g', models.PositiveIntegerField(verbose_name='Poids maximum (grammes)')),
                ('prix_relais_cents', models.PositiveIntegerField(verbose_name='Prix point relais (centimes)')),
                ('prix_domicile_cents', models.PositiveIntegerField(verbose_name='Prix domicile (centimes)')),
            ],
            options={
                'verbose_name': 'Tranche de frais de port',
                'verbose_name_plural': 'Tranches de frais de port',
                'ordering': ['poids_max_g'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='poids_g',
            field=models.PositiveIntegerField(default=500, help_text='Poids unitaire du produit. Sert au calcul des frais de port (au poids).', verbose_name='Poids (grammes)'),
        ),
        # Seed de la grille de départ (reverse : le CreateModel supprime déjà la table).
        migrations.RunPython(seed_tranches, migrations.RunPython.noop),
    ]
