# Generated by Django 5.2.15 on 2026-10-03 12:41

from django.db import migrations, models


def annuler_commandes_cb_en_attente(apps, schema_editor):
    """Les commandes CB jamais réglées (Stripe non abouti) deviennent « annulées »
    et archivées : leur statut disparaît des choix, plus rien ne pourra les passer
    à « payé », et elles ne doivent plus encombrer l'onglet « à traiter ».

    Les commandes historiques en ``mode_paiement="cb"`` (payées ou annulées)
    sont volontairement laissées telles quelles : la valeur n'est plus dans les
    choix et s'affiche brute, mais l'historique reste exact.

    Irréversible : le rollback (noop) ne restaure ni ce statut ni les sessions
    Stripe supprimées avec le champ.
    """
    Commande = apps.get_model("boutique", "Commande")
    Commande.objects.filter(statut="en_attente_paiement").update(
        statut="annule", archive=True, lu=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_grille_frais_port_reelle'),
    ]

    operations = [
        migrations.RunPython(annuler_commandes_cb_en_attente, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='commande',
            name='stripe_session_id',
        ),
        migrations.AlterField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente_reglement', 'En attente de règlement'), ('paye', 'Payé'), ('annule', 'Annulé')], max_length=30, verbose_name='Statut'),
        ),
    ]
