# Generated by Django 5.1.15 on 2026-05-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('seo_title', models.CharField(blank=True, help_text='Titre affiché par Google (~60 caractères). Laisser vide pour titre auto.', max_length=70, verbose_name='Titre SEO')),
                ('seo_description', models.CharField(blank=True, help_text='Description affichée par Google (~150 caractères).', max_length=160, verbose_name='Description SEO')),
                ('og_image', models.ImageField(blank=True, help_text="Image affichée lors d'un partage sur les réseaux sociaux.", null=True, upload_to='og/', verbose_name='Image de partage')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Identifiant')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('published', models.BooleanField(default=True, verbose_name='Publiée')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('type', models.CharField(choices=[('heading', 'Titre'), ('text', 'Texte'), ('quote', 'Citation'), ('image', 'Image'), ('separator', 'Séparateur'), ('gallery', 'Galerie')], max_length=20, verbose_name='Type')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Contenu')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Bloc de contenu',
                'verbose_name_plural': 'Blocs de contenu',
                'ordering': ['position', 'id'],
            },
        ),
    ]
