# Generated by Django 5.1.15 on 2026-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('hero_titre', models.TextField(blank=True, help_text="Titre principal de la page d'accueil. HTML autorisé : <em>…</em> pour l'accent terracotta, <br> pour les retours à la ligne.", verbose_name='Titre du hero')),
                ('hero_pitch', models.TextField(blank=True, help_text="Paragraphe d'introduction sous le titre.", verbose_name='Pitch du hero')),
                ('hero_image', models.ImageField(blank=True, help_text='Optionnelle. Si renseignée, remplace la couverture-placeholder à droite du titre.', null=True, upload_to='accueil/', verbose_name='Image du hero')),
                ('pull_quote_texte', models.TextField(blank=True, help_text='Phrase mise en exergue entre le hero et les actualités.', verbose_name='Citation centrale')),
                ('pull_quote_auteur', models.CharField(blank=True, max_length=120, verbose_name='Auteur de la citation')),
                ('dedicaces_intro', models.TextField(blank=True, help_text='Texte sous le titre « Dédicaces & actualités ».', verbose_name='Introduction du bloc Dédicaces')),
                ('temoignages_intro', models.TextField(blank=True, help_text='Texte affiché au-dessus du carrousel de témoignages (optionnel).', verbose_name='Introduction du bloc Témoignages')),
            ],
            options={
                'verbose_name': "Page d'accueil",
                'verbose_name_plural': "Page d'accueil",
            },
        ),
    ]
