# Generated by Django 5.1.15 on 2026-05-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_accueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='accueil',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Image affichée lors d'un partage sur les réseaux sociaux.", null=True, upload_to='og/', verbose_name='Image de partage'),
        ),
        migrations.AddField(
            model_name='accueil',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Description affichée par Google (~150 caractères).', max_length=160, verbose_name='Description SEO'),
        ),
        migrations.AddField(
            model_name='accueil',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Titre affiché par Google (~60 caractères). Laisser vide pour titre auto.', max_length=70, verbose_name='Titre SEO'),
        ),
    ]
