# Generated by Django 5.1.15 on 2026-05-23 15:10

import apps.core.uploads
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_accueil_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueil',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optionnelle. Si renseignée, remplace la couverture-placeholder à droite du titre.', null=True, upload_to=apps.core.uploads.accueil_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Image du hero'),
        ),
        migrations.AlterField(
            model_name='accueil',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Image affichée lors d'un partage sur les réseaux sociaux.", null=True, upload_to=apps.core.uploads.og_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Image de partage'),
        ),
        migrations.AlterField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Image affichée lors d'un partage sur les réseaux sociaux.", null=True, upload_to=apps.core.uploads.og_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Image de partage'),
        ),
    ]
