# Generated by Django 5.1.15 on 2026-05-23 15:50

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_accueil_hero_image_alter_accueil_og_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueil',
            name='dedicaces_intro',
            field=apps.core.fields.RichTextField(blank=True, help_text='Texte sous le titre « Dédicaces & actualités ».', verbose_name='Introduction du bloc Dédicaces'),
        ),
        migrations.AlterField(
            model_name='accueil',
            name='hero_pitch',
            field=apps.core.fields.RichTextField(blank=True, help_text="Paragraphe d'introduction sous le titre.", verbose_name='Pitch du hero'),
        ),
        migrations.AlterField(
            model_name='accueil',
            name='hero_titre',
            field=apps.core.fields.RichTextField(blank=True, help_text="Titre principal de la page d'accueil. Utilise l'italique pour l'accent terracotta.", mode='inline', verbose_name='Titre du hero'),
        ),
        migrations.AlterField(
            model_name='accueil',
            name='pull_quote_texte',
            field=apps.core.fields.RichTextField(blank=True, help_text='Phrase mise en exergue entre le hero et les actualités.', mode='inline', verbose_name='Citation centrale'),
        ),
        migrations.AlterField(
            model_name='accueil',
            name='temoignages_intro',
            field=apps.core.fields.RichTextField(blank=True, help_text='Texte affiché au-dessus du carrousel de témoignages (optionnel).', verbose_name='Introduction du bloc Témoignages'),
        ),
    ]
