# Generated by Django 5.1.15 on 2026-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_accueilimage_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accueil',
            name='hero_image',
        ),
    ]
