# Generated by Django 5.1.15 on 2026-05-23 20:38

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_accueil_delai_rotation_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='accueilimage',
            name='legende',
            field=apps.core.fields.RichTextField(blank=True, help_text="Texte affiché sous l'image dans le carrousel. Gras / italique autorisés.", mode='inline', verbose_name='Légende'),
        ),
    ]
