# Generated by Django 5.1.15 on 2026-06-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_accueilimage_legende'),
    ]

    operations = [
        migrations.AddField(
            model_name='accueil',
            name='pull_quote_commentaire',
            field=models.CharField(blank=True, help_text="Quelques mots, affichés sous l'auteur, sur la citation ou son auteur (optionnel).", max_length=300, verbose_name='Commentaire'),
        ),
    ]
