# Generated by Django 5.1.15 on 2026-05-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0002_billetimagecontenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetimagecontenu',
            name='largeur',
            field=models.CharField(choices=[('100', 'Pleine largeur'), ('75', '3/4 de la largeur'), ('50', 'Moitié'), ('33', 'Tiers'), ('25', 'Quart')], default='100', help_text="Proportion de la largeur du bloc occupée par l'image. Le ratio est conservé.", max_length=3, verbose_name='Largeur'),
        ),
    ]
