# Generated by Django 5.1.15 on 2026-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0003_billetimagecontenu_largeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetimagecontenu',
            name='alignement',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'À gauche (texte autour)'), ('right', 'À droite (texte autour)')], default='center', help_text="Position de l'image. À gauche ou à droite, le texte s'enroule autour.", max_length=6, verbose_name='Alignement'),
        ),
    ]
