# Generated by Django 5.1.15 on 2026-05-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0004_billetimagecontenu_alignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetimagecontenu',
            name='sans_habillage',
            field=models.BooleanField(default=False, help_text="L'image reste seule sur sa ligne, à sa largeur : le texte ne s'enroule pas autour. Sans effet sur une image centrée.", verbose_name='Pas de texte à côté'),
        ),
        migrations.AlterField(
            model_name='billetimagecontenu',
            name='alignement',
            field=models.CharField(choices=[('center', 'Centré'), ('left', 'À gauche (texte autour)'), ('right', 'À droite (texte autour)')], default='center', help_text="Position de l'image. À gauche ou à droite, le texte s'enroule autour (sauf si « Pas de texte à côté » est coché).", max_length=6, verbose_name='Alignement'),
        ),
    ]
