# Generated by Django 5.1.15 on 2026-05-23 13:11

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10, verbose_name='Type')),
                ('categorie', models.CharField(choices=[('bertin', 'Jacques Bertin'), ('livre', 'Le livre'), ('dedicace', 'Dédicaces'), ('auteur', 'Bruno Boulais'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie')),
                ('fichier', models.FileField(upload_to='galerie/', verbose_name='Fichier')),
                ('legende', models.CharField(blank=True, max_length=300, verbose_name='Légende')),
                ('alt', models.CharField(blank=True, help_text="Décrit l'image pour les lecteurs d'écran.", max_length=200, verbose_name='Texte alternatif')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
