# Generated by Django 5.1.15 on 2026-05-23 15:10

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=models.FileField(upload_to=apps.core.uploads.galerie_upload_to, verbose_name='Fichier'),
        ),
    ]
