# Generated by Django 5.1.15 on 2026-05-24 21:29

import apps.core.uploads
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_alter_media_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=models.FileField(upload_to=apps.core.uploads.galerie_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'mp4', 'webm', 'mov']), apps.core.validators.validate_media_size], verbose_name='Fichier'),
        ),
    ]
