# Generated by Django 5.1.15 on 2026-05-25 14:24

import apps.core.uploads
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chanson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('url_youtube', models.URLField(max_length=300, verbose_name='Lien YouTube')),
                ('illustration', models.ImageField(blank=True, upload_to=apps.core.uploads.discotheque_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), apps.core.validators.validate_image_size], verbose_name='Illustration')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('album', models.CharField(blank=True, max_length=200, verbose_name='Album')),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Chanson',
                'verbose_name_plural': 'Chansons',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
