# Generated by Django 5.1.15 on 2026-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chanson',
            options={'ordering': [models.Case(models.When(position=0, then=models.Value(1)), default=models.Value(0), output_field=models.IntegerField()), 'position', '-created_at'], 'verbose_name': 'Chanson', 'verbose_name_plural': 'Chansons'},
        ),
    ]
