# Generated by Django 5.1.15 on 2026-06-07 12:35

import apps.core.uploads
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discotheque', '0003_discothequepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanson',
            name='audio',
            field=models.FileField(blank=True, upload_to=apps.core.uploads.discotheque_audio_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'ogg', 'wav', 'aac']), apps.core.validators.validate_audio_size], verbose_name='Fichier audio'),
        ),
        migrations.AddField(
            model_name='chanson',
            name='date_enregistrement',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'enregistrement"),
        ),
        migrations.AddField(
            model_name='chanson',
            name='type',
            field=models.CharField(choices=[('chanson', 'Chanson (YouTube)'), ('enregistrement', 'Enregistrement téléphonique')], default='chanson', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='chanson',
            name='url_youtube',
            field=models.URLField(blank=True, max_length=300, verbose_name='Lien YouTube'),
        ),
    ]
